version: '3.8'

services:
  auth-staging:
    build:
      context: ./auth
      dockerfile: Dockerfile.staging
    env_file:
      - /root/config/auth.env.txt
    container_name: auth-staging
    restart: always
    ports:
      - 3001:3001
    networks:
      - app-network

  bank-staging:
    build:
      context: ./bank
      dockerfile: Dockerfile.staging
    env_file:
      - /root/config/bank.env.txt
    container_name: bank-staging
    restart: always
    ports:
      - 3003:3003
    networks:
      - app-network

  user-staging:
    build:
      context: ./user
      dockerfile: Dockerfile.staging
    env_file:
      - /root/config/user.env.txt
    container_name: user-staging
    restart: always
    ports:
      - 3002:3002
    networks:
      - app-network

networks:
  app-network:
    external: true
