version: '3.8'

services:
  auth-prod:
    build:
      context: ./auth
      dockerfile: Dockerfile.prod
    container_name: auth-prod
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - rabbitmq

  bank-prod:
    build:
      context: ./bank
      dockerfile: Dockerfile.prod
    container_name: bank-prod
    restart: always
    ports:
      - 3003:3003
    depends_on:
      - postgres
      - rabbitmq
      - redis

  user-prod:
    build:
      context: ./user
      dockerfile: Dockerfile.prod
    container_name: user-prod
    restart: always
    ports:
      - 3002:3002
    depends_on:
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    restart: always
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
