version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - ./configs/env.txt
    ports:
      - 5432:5432
    volumes:
      - ./postgres-backup:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
