version: '3.8'
services:
  s-user:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: s-user
    env_file:
      - /root/config/s-user.env.txt
    container_name: s-user
    ports:
      - 3002:3002
