version: '3.9'
name: s-user
services:
  s-user:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: s-user
    env_file:
      - /root/config/s-user.env.txt
    container_name: s-user
    restart: always
    ports:
      - 3002:3002
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
