version: '3.8'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - /root/config/user.env.txt
    container_name: user
    restart: always
    ports:
      - 3002:3002
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
