version: '3.8'
services:
  s-user:
    image: mohammadnowresideh1997/s-user
    env_file:
      - /root/config/s-user.env.txt
    container_name: s-user
    ports:
      - 3002:3002
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
