version: '3.8'
services:
  c-auth:
    build:
      context: .
      dockerfile: Dockerfile.staging
      args:
        NODE_ENV: ${NODE_ENV}
        PUBLIC_PATH: ${PUBLIC_PATH}
        AUTH_SERVICE: ${AUTH_SERVICE}
        CACHE_SECRET_KEY: ${CACHE_SECRET_KEY}
        CONTAINER_APP: ${CONTAINER_APP}
        AUTH_APP: ${AUTH_APP}
        BANK_APP: ${BANK_APP}
    image: c-auth
    container_name: c-auth
    ports:
      - 3005:3005
