version: '3.8'
services:
  c-auth:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: c-auth
    env_file:
      - /root/config/c-auth.env.txt
    container_name: c-auth
    restart: always
    ports:
      - 3005:3005
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
