version: '3.8'
name: s-auth
services:
  s-auth:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: s-auth
    env_file:
      - /root/config/s-auth.env.txt
    container_name: s-auth
    restart: always
    ports:
      - 3001:3001
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
