FROM node:18.10.0-alpine

WORKDIR /usr/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install 

COPY . .

RUN npm run webpack:build

EXPOSE 3006

CMD [ "npm", "run", "start:prod" ]