version: '3.8'
name: s-bank
services:
  s-bank:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: s-bank
    env_file:
      - /root/config/s-bank.env.txt
    container_name: s-bank
    restart: always
    ports:
      - 3003:3003
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
