version: '3.8'
services:
  s-bank:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: s-bank
    env_file:
      - /root/config/s-bank.env.txt
    container_name: s-bank
    ports:
      - 3003:3003
