name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'servers/auth/**'

defaults:
  run:
    working-directory: servers/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
