name: Build

on:
  push:
    branches:
      - integration

jobs:
  build:
    name: Build the server projects
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing the node_modules packages
        run: npm install

      - name: Running the build process
        run: npm run build
