name: Build

on:
  push:
    branches:
      - integration

jobs:
  build-clients:
    name: Build the client projects
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing the node_modules packages of the root
        run: npm install

      - name: Installing the node_modules packages of the clients
        run: npm run install:repos

      - name: Running the build process
        run: npm run webpack:build:repos:prod

  build-servers:
    name: Build the server projects
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing the node_modules packages of the root
        run: npm install

      - name: Installing the node_modules packages of the servers
        run: npm run install:repos

      - name: Running the build process
        run: npm run build:repos
