name: Publish Docker image

on:
  push:
    branches:
      - staging

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ../servers/auth/Dockerfile.staging
            image: ${{ secrets.DOCKER_USERNAME }}/auth-staging:latest
          - dockerfile: ../servers/bank/Dockerfile.staging
            image: ${{ secrets.DOCKER_USERNAME }}/bank-staging:latest
          - dockerfile: ../servers/user/Dockerfile.staging
            image: ${{ secrets.DOCKER_USERNAME }}/user-staging:latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ../
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
