name: Publish Docker image

on:
  push:
    branches:
      - staging

jobs:
  build-push-action:
    name: Building the images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./servers/auth/Dockerfile.staging
            image: mohammadnowresideh1997/s-auth
            context: ./servers/auth

          - dockerfile: ./servers/bank/Dockerfile.staging
            image: mohammadnowresideh1997/s-bank
            context: ./servers/bank

          - dockerfile: ./servers/user/Dockerfile.staging
            image: mohammadnowresideh1997/s-user
            context: ./servers/user

          - dockerfile: ./clients/auth/Dockerfile.staging
            image: mohammadnowresideh1997/c-auth
            context: ./clients/auth
            build-args: |
              PUBLIC_PATH=${{ secrets.C_AUTH_PUBLIC_PATH }}
              AUTH_SERVICE=${{ secrets.AUTH_SERVICE }}
              CACHE_SECRET_KEY=${{ secrets.C_AUTH_CACHE_SECRET_KEY }}
              CONTAINER_APP=${{ secrets.CONTAINER_APP }}
              AUTH_APP=${{ secrets.AUTH_APP }}
              BANK_APP=${{ secrets.BANK_APP }}

          # - dockerfile: ./clients/bank/Dockerfile.staging
          #   image: mohammadnowresideh1997/c-bank
          #   context: ./clients/bank

          # - dockerfile: ./clients/container/Dockerfile.staging
          #   image: mohammadnowresideh1997/c-container
          #   context: ./clients/container
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'staging') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.secret }}

  deploying-ssh:
    needs: build-push-action
    name: Running the deployment on the vps server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Executing the remote ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 60m
          script: |
            cd app
            npm run docker:compose:staging:down
            npm run docker:rmi
            npm run docker:compose:staging:up
