name: Publish Docker image

on:
  push:
    branches:
      - staging

jobs:
  build-push-action:
    name: Building the images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./servers/auth/Dockerfile.staging
            image: mohammadnowresideh1997/auth-server-staging
            context: ./servers/auth
          - dockerfile: ./servers/bank/Dockerfile.staging
            image: mohammadnowresideh1997/bank-server-staging
            context: ./servers/bank
          - dockerfile: ./servers/user/Dockerfile.staging
            image: mohammadnowresideh1997/user-server-staging
            context: ./servers/user
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploying-ssh:
    needs: build-push-action
    name: Running the deployment on the vps server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Executing the remote ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd bank-system
            git pull origin staging
            cd servers/auth
            npm run docker:compose:staging:up
