name: user

on:
  push:
    branches:
      - master
    paths:
      - 'servers/user/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./servers/user

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
